# Generated by Django 3.1.2 on 2020-11-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201104_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.AddField(
            model_name='user',
            name='modalidad',
            field=models.CharField(choices=[('Asesor', 'Asesor'), ('Promotor', 'Promotor')], default='Promotor', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='bienvenida_txt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='despedida_txt',
            field=models.TextField(blank=True),
        ),
    ]
