# Generated by Django 3.1.2 on 2020-11-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201105_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contraseña',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=40),
        ),
    ]
