# Generated by Django 3.1.2 on 2020-11-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201105_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Apellidos'),
        ),
    ]
