# Generated by Django 3.1.2 on 2020-11-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201105_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='modalidad',
            field=models.CharField(choices=[('Asesor', 'Asesor'), ('Promotor', 'Promotor')], max_length=10),
        ),
    ]
