# Generated by Django 3.1.2 on 2020-11-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201105_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='modalidad',
            field=models.CharField(choices=[('Asesor', 'Asesor'), ('Promotor', 'Promotor')], default='Promotor', max_length=10),
        ),
    ]
