# Generated by Django 3.1.2 on 2020-11-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201106_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='modalidad',
            field=models.CharField(choices=[('Asesor', 'Asesor'), ('Promotor', 'Promotor')], default='Asesor', max_length=10),
        ),
    ]
