# Generated by Django 3.1.2 on 2020-11-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201110_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
