# Generated by Django 3.1.2 on 2020-11-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20201111_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.TextField(),
        ),
    ]
