# Generated by Django 3.1.2 on 2020-11-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20201111_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(upload_to='static/img/promotores'),
        ),
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
