# Generated by Django 3.1.2 on 2020-11-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201119_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='static/img/ic-2.png', upload_to='static/img/promotores'),
        ),
    ]
