# Generated by Django 3.1.2 on 2020-11-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20201120_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='staticfiles/img/ic-2.png', upload_to='staticfiles/img/promotores'),
        ),
    ]
