# Generated by Django 3.1.2 on 2020-11-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20201130_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='static/img/ic-2.png', upload_to='static/img/promotores'),
        ),
    ]
