# Generated by Django 3.1.2 on 2020-12-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20201130_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='staticfiles/img/promotores/logos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='staticfiles/img/ic-2.png', upload_to='staticfiles/img/promotores'),
        ),
    ]
