# Generated by Django 3.1.2 on 2020-12-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20201204_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='static/img/promotores/logos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='static/img/ic-2.png', upload_to='static/img/promotores'),
        ),
    ]
