# Generated by Django 3.1.2 on 2020-12-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20201209_1904'),
        ('users', '0027_auto_20201209_1601'),
    ]

    operations = [
    ]
