# Generated by Django 3.1.2 on 2020-12-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20201217_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='staticfiles/img/promotores/logos'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='staticfiles/img/ic-2.png', upload_to='staticfiles/img/promotores'),
        ),
    ]
