# Generated by Django 3.1.2 on 2021-03-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20201218_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='static/img/ic-2.png', upload_to='static/img/promotores'),
        ),
    ]
