# Generated by Django 3.1.7 on 2021-03-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20210303_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='staticfiles/img/promotores/logos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='staticfiles/img/ic-2.png', upload_to='staticfiles/img/promotores'),
        ),
    ]
