# Generated by Django 3.1.2 on 2020-11-23 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('factor_millar', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('castigo', models.FloatField()),
                ('endeudamiento', models.FloatField()),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calc.banco')),
            ],
        ),
    ]
