# Generated by Django 3.1.1 on 2020-10-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0002_auto_20200929_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesores',
            name='contraseña',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='asesores',
            name='puesto',
            field=models.CharField(default=None, max_length=140),
        ),
        migrations.AddField(
            model_name='asesores',
            name='telefono',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
