# Generated by Django 3.1.1 on 2020-10-02 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0003_auto_20201001_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesores',
            name='contraseña',
        ),
    ]
