# Generated by Django 3.1.1 on 2020-10-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0004_remove_asesores_contraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesores',
            name='puesto',
        ),
        migrations.RemoveField(
            model_name='asesores',
            name='telefono',
        ),
    ]
