# Generated by Django 3.1.1 on 2020-10-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0005_auto_20201002_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesores',
            name='puesto',
            field=models.CharField(default=None, max_length=140),
        ),
        migrations.AddField(
            model_name='asesores',
            name='telefono',
            field=models.CharField(default=None, max_length=140),
        ),
    ]
