# Generated by Django 3.1.1 on 2020-10-08 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0006_auto_20201007_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesores',
            name='contraseña',
        ),
    ]
