# Generated by Django 3.1.2 on 2020-10-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0008_auto_20201007_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesores',
            name='puesto',
            field=models.CharField(choices=[('1', 'Asesor'), ('2', 'Promotor')], default='1', max_length=10),
        ),
    ]
