# Generated by Django 3.1.2 on 2020-10-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0009_asesores_puesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesores',
            name='pswd',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='asesores',
            name='telefono',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='asesores',
            name='puesto',
            field=models.CharField(choices=[('Asesor', 'Asesor'), ('Promotor', 'Promotor')], max_length=10),
        ),
    ]
