# Generated by Django 3.1.2 on 2020-10-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0010_auto_20201016_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesores',
            name='pswd',
            field=models.CharField(default='', max_length=20),
        ),
    ]
