# Generated by Django 3.1.2 on 2020-10-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0011_auto_20201016_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesores',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
