# Generated by Django 3.1.2 on 2020-10-16 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0012_auto_20201016_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesores',
            name='telefono',
        ),
    ]
