# Generated by Django 3.1.2 on 2020-10-30 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0013_remove_asesores_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asesores',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='asesores',
            name='puesto',
        ),
        migrations.CreateModel(
            name='Promotores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('usuario', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=140)),
                ('pswd', models.CharField(default='', max_length=20)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asesores.asesores')),
            ],
        ),
    ]
