# Generated by Django 3.1.2 on 2020-11-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0014_auto_20201030_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotores',
            name='empresa',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='promotores',
            name='foto',
            field=models.ImageField(default='', upload_to='static/img/promotores'),
        ),
        migrations.AddField(
            model_name='promotores',
            name='logo',
            field=models.ImageField(default='', upload_to='static/img/promotores/logos'),
        ),
        migrations.AddField(
            model_name='promotores',
            name='telefono',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='promotores',
            name='texto_bienvenida',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='promotores',
            name='texto_despedida',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='promotores',
            name='url',
            field=models.URLField(default='', max_length=140),
        ),
    ]
