# Generated by Django 3.1.1 on 2020-10-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=140)),
                ('telefono', models.CharField(max_length=140)),
                ('promotor', models.CharField(max_length=140)),
            ],
        ),
    ]
