# Generated by Django 3.1.2 on 2020-10-30 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0014_auto_20201030_1059'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='promotor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asesores.promotores'),
        ),
    ]
