# Generated by Django 3.1.2 on 2020-11-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='alcance_credito',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='tramite',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
