# Generated by Django 3.1.2 on 2020-11-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20201119_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='actividad',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='actividad_co_acreditado',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='años_credito',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='busqueda',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='credito_cofinanciado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='ingreso_mensual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='ingreso_mensual_co_acreditado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='inmueble_identificado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='institucion',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='institucion_hipotecaria',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='instituciones_co_acreditado',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='moneda_credito',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='mostrar_mayor_ingreso',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='pagando_credito_inmb',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='pagando_credito_inmb_co_acreditado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='pago_credito',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='pago_mensual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='pagos_pactados',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='puntualidad_pagos',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='saldo_actual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='tiempo_pagando',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='valor_inmueble',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='valor_proyecto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
