# Generated by Django 3.1.1 on 2020-11-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20201123_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='giro_actividad',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='giro_actividad_co_acreditado',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
