# Generated by Django 3.1.1 on 2020-11-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20201123_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='inmueble_identificado',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='mostrar_mayor_ingreso',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='pagando_credito_inmb',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='pagando_credito_inmb_co_acreditado',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='credito_cofinanciado',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
