# Generated by Django 3.1.1 on 2020-11-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20201123_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='tiempo_pagando',
            new_name='tiempo_pagando_años',
        ),
        migrations.AddField(
            model_name='clientes',
            name='tiempo_pagando_meses',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
