# Generated by Django 3.1.1 on 2020-11-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20201123_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='valor_proyecto',
        ),
    ]
