# Generated by Django 3.1.2 on 2020-11-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_remove_clientes_valor_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='afirme',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clientes',
            name='banamex',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clientes',
            name='banorte',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clientes',
            name='banregio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clientes',
            name='bx',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clientes',
            name='hsbc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clientes',
            name='santander',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clientes',
            name='scotiabanck',
            field=models.FloatField(default=0.0),
        ),
    ]
