# Generated by Django 3.1.2 on 2020-11-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20201130_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='afirme',
            field=models.CharField(default='0.0', max_length=40),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='banamex',
            field=models.CharField(default='0.0', max_length=40),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='banorte',
            field=models.CharField(default='0.0', max_length=40),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='banregio',
            field=models.CharField(default='0.0', max_length=40),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='bx',
            field=models.CharField(default='0.0', max_length=40),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='hsbc',
            field=models.CharField(default='0.0', max_length=40),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='santander',
            field=models.CharField(default='0.0', max_length=40),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='scotiabanck',
            field=models.CharField(default='0.0', max_length=40),
        ),
    ]
