# Generated by Django 3.1.2 on 2020-11-30 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_auto_20201130_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='alcance_credito',
        ),
    ]
