# Generated by Django 3.1.2 on 2020-12-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_remove_clientes_alcance_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='inmueble_identificado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='pagando_credito_inmb',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='pagando_credito_inmb_co_acreditado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
