# Generated by Django 3.1.2 on 2020-12-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_auto_20201204_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='pagando_credito_inmb',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='pagando_credito_inmb_co_acreditado',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
