# Generated by Django 3.1.2 on 2020-12-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_auto_20201204_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='inmueble_identificado',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
