# Generated by Django 3.1.2 on 2020-12-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_auto_20201204_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tramite',
            field=models.CharField(blank=True, max_length=140, null=True, unique=True),
        ),
    ]
