# Generated by Django 3.1.2 on 2020-12-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_auto_20201209_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tramite',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
