# Generated by Django 3.1.2 on 2020-12-16 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0018_auto_20201215_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de creacion'),
        ),
    ]
