# Generated by Django 3.1.2 on 2020-12-16 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_clientes_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='fecha de creacion'),
        ),
    ]
