# Generated by Django 3.1.2 on 2020-12-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_auto_20201215_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='co_acreditado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
