# Generated by Django 3.1.2 on 2020-12-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0021_clientes_co_acreditado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='co_acreditado',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
